[package]
name = "data"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.9", default-features = false, features = ["runtime-tokio", "tls-rustls", "any", "postgres", "mysql", "sqlite"] }
redis = { version = "1.6", default-features = false, features = ["tokio-rustls-comp", "connection-manager"] }
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"] }
